import { useMemo, useState } from 'react'

// Hosts that block CORS + return 200 on rate-limit → route through our dev/preview
// proxy (/__svg) which detects the error server-side and 502s so onError fires.
const STAT_HOSTS = [
  'github-readme-stats.vercel.app',
  'streak-stats.demolab.com',
  'github-profile-trophy.vercel.app',
  'github-readme-activity-graph.vercel.app',
  'komarev.com',
  'quotes-github-readme.vercel.app',
  'readme-typing-svg.demolab.com',
  'spotify-github-profile.kittinanx.com',
]

type Category = 'action' | 'service' | 'generic'

function classify(src: string): { category: Category; attempts: string[] } {
  let host = ''
  try {
    host = new URL(src).host
  } catch {
    /* relative/invalid */
  }
  const isActionOutput = src.includes('raw.githubusercontent.com') && (src.includes('/output/') || src.includes('/profile-3d-contrib/'))
  if (isActionOutput) return { category: 'action', attempts: [src] }
  if (STAT_HOSTS.includes(host)) {
    // try the proxy first (real detection), fall back to direct (e.g. prod with no proxy)
    return { category: 'service', attempts: [`/__svg?u=${encodeURIComponent(src)}`, src] }
  }
  return { category: 'generic', attempts: [src] }
}

// alt text (set in generate.ts) → friendly widget name + skeleton shape
function meta(alt: string): { name: string; shape: string } {
  const a = alt.toLowerCase()
  if (a.includes('streak')) return { name: 'Streak stats', shape: 'streak' }
  if (a.includes('github stats')) return { name: 'GitHub stats', shape: 'stats' }
  if (a.includes('top languages')) return { name: 'Top languages', shape: 'langs' }
  if (a.includes('trophies') || a.includes('trophy')) return { name: 'GitHub trophies', shape: 'trophies' }
  if (a.includes('activity')) return { name: 'Activity graph', shape: 'graph' }
  if (a.includes('snake')) return { name: 'Contribution snake', shape: 'grid' }
  if (a.includes('pacman')) return { name: 'Pac-Man graph', shape: 'grid' }
  if (a.includes('3d')) return { name: '3D contribution graph', shape: 'grid' }
  if (a.includes('profile views') || a.includes('views')) return { name: 'Profile views', shape: 'pill' }
  if (a.includes('followers')) return { name: 'Followers', shape: 'pill' }
  if (a.includes('quote')) return { name: 'Dev quote', shape: 'quote' }
  if (a.includes('spotify')) return { name: 'Now playing', shape: 'stats' }
  if (a.includes('typing')) return { name: 'Typing banner', shape: 'quote' }
  return { name: alt || 'Widget', shape: 'rows' }
}

function reasonFor(category: Category): string {
  if (category === 'action')
    return "Generated by a GitHub Action — it shows up once you add the workflow (Actions tab) and it runs the first time."
  if (category === 'service')
    return 'The stats service is rate-limited or unreachable right now. It usually recovers within a few minutes — or self-host it with your own GitHub token to remove limits entirely.'
  return "Couldn't load — the service may be down, or there's no data for this username yet."
}

function Skeleton({ shape }: { shape: string }) {
  const bar = 'rounded bg-white/10'
  if (shape === 'streak')
    return (
      <div className="flex items-center justify-around gap-3 py-1">
        {[0, 1, 2].map((i) => (
          <div key={i} className="flex flex-col items-center gap-1.5">
            <div className={`h-9 w-9 rounded-full border-2 border-white/10 ${i === 1 ? 'border-white/20' : ''}`} />
            <div className={`h-1.5 w-12 ${bar}`} />
          </div>
        ))}
      </div>
    )
  if (shape === 'trophies')
    return (
      <div className="flex flex-wrap gap-1.5 py-1">
        {Array.from({ length: 7 }).map((_, i) => (
          <div key={i} className="h-9 w-9 rounded-md border border-white/10" />
        ))}
      </div>
    )
  if (shape === 'grid')
    return (
      <div className="grid gap-[3px] py-1" style={{ gridTemplateColumns: 'repeat(20, 1fr)' }}>
        {Array.from({ length: 60 }).map((_, i) => (
          <div key={i} className="aspect-square rounded-[1px] bg-white/10" style={{ opacity: 0.4 + ((i * 7) % 5) * 0.12 }} />
        ))}
      </div>
    )
  if (shape === 'graph')
    return (
      <svg viewBox="0 0 100 30" className="w-full" preserveAspectRatio="none">
        <polyline points="0,24 16,14 32,18 48,8 64,13 80,5 100,10" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-white/20" />
      </svg>
    )
  if (shape === 'langs')
    return (
      <div className="space-y-1.5 py-1">
        {[80, 60, 45, 30].map((w, i) => (
          <div key={i} className={`h-2 ${bar}`} style={{ width: `${w}%` }} />
        ))}
      </div>
    )
  if (shape === 'pill') return <div className="h-5 w-28 rounded bg-white/10" />
  if (shape === 'quote')
    return (
      <div className="space-y-1.5 py-1">
        <div className={`h-2 w-full ${bar}`} />
        <div className={`h-2 w-2/3 ${bar}`} />
      </div>
    )
  return (
    <div className="space-y-2 py-1">
      <div className={`h-2 w-3/4 ${bar}`} />
      <div className={`h-2 w-1/2 ${bar}`} />
      <div className={`h-2 w-2/3 ${bar}`} />
    </div>
  )
}

export default function SmartImg({
  src = '',
  alt = '',
  width,
  height,
}: {
  src?: string
  alt?: string
  width?: string | number
  height?: string | number
}) {
  const { category, attempts } = useMemo(() => classify(src), [src])
  const [i, setI] = useState(0)
  const [loaded, setLoaded] = useState(false)
  const failed = i >= attempts.length

  if (failed) {
    // small inline icons (about/skill/social) degrade to inline text — never the big card
    if (category === 'generic') {
      return <span className="align-middle text-sm opacity-70">{alt || '•'}</span>
    }
    const m = meta(alt)
    const isAction = category === 'action'
    return (
      <span
        className="my-1 inline-block w-full max-w-[480px] rounded-xl border border-dashed p-3 text-left align-top"
        style={{ borderColor: isAction ? 'rgba(251,191,36,.35)' : 'rgba(255,255,255,.18)', background: 'rgba(255,255,255,.02)' }}
      >
        <span className="mb-2 flex items-center gap-2 text-[13px] font-semibold text-white/70">
          <span className={`flex h-5 w-5 items-center justify-center rounded ${isAction ? 'bg-amber-400/20 text-amber-300' : 'bg-white/10 text-white/50'}`}>
            {isAction ? '⚙️' : '○'}
          </span>
          {m.name}
          <span className="ml-auto rounded-full px-2 py-0.5 text-[10px] font-medium" style={{ background: isAction ? 'rgba(251,191,36,.12)' : 'rgba(255,255,255,.06)', color: isAction ? '#fcd34d' : 'rgba(255,255,255,.5)' }}>
            {isAction ? 'pending action' : 'no data'}
          </span>
        </span>
        <span className="block text-white/40">
          <Skeleton shape={m.shape} />
        </span>
        <span className="mt-2 flex gap-1.5 text-[11px] leading-snug text-white/45">
          <span className="shrink-0">ⓘ</span>
          <span>{reasonFor(category)}</span>
        </span>
      </span>
    )
  }

  return (
    <span className="relative inline-block align-middle">
      {!loaded && <span className="absolute inset-0 animate-pulse rounded bg-white/[0.04]" />}
      <img
        src={attempts[i]}
        alt={alt}
        width={width}
        height={height}
        onLoad={() => setLoaded(true)}
        onError={() => {
          setLoaded(false)
          setI((n) => n + 1)
        }}
        style={{ display: 'inline-block', maxWidth: '100%' }}
      />
    </span>
  )
}
